default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: digital_bazaar_development

test:
  <<: *default
  database: digital_bazaar_test

production:
  <<: *default
  database: digital_bazaar_production
  username: digital_bazaar
  password: <%= ENV["DIGITAL_BAZAAR_DATABASE_PASSWORD"] %>
